const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true, channel:'chrome'});
  const context = await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:8765/');
  assert(page.url().endsWith('/login'));
  await page.locator('#password').fill('browser-test-password');
  await Promise.all([page.waitForURL('http://127.0.0.1:8765/'),page.getByRole('button',{name:'Continue to SmartLook'}).click()]);
  async function send(message) {
    await page.locator('#messageInput').fill(message);
    const response = page.waitForResponse(r=>r.url().endsWith('/api/chat'));
    await page.locator('#messageInput').press('Enter');
    assert.equal((await response).status(),200);
    await page.waitForFunction(()=>!isLoading);
  }
  await send('first conversation');
  assert((await page.locator('#messagesContainer').innerText()).includes('Previous messages: 0'));
  await send('follow up');
  assert((await page.locator('#messagesContainer').innerText()).includes('Previous messages: 2'));
  await page.reload();
  await page.waitForFunction(()=>currentChatId && chatHistory.length===4);
  await send('after reload');
  assert((await page.locator('#messagesContainer').innerText()).includes('Previous messages: 4'));
  await page.evaluate(()=>newChat());
  await send('second conversation');
  assert((await page.locator('#messagesContainer').innerText()).includes('Previous messages: 0'));
  await page.locator('.history-item').filter({hasText:'first conversation'}).click();
  await send('resume old conversation');
  assert((await page.locator('#messagesContainer').innerText()).includes('Previous messages: 6'));
  await send('<img src=x onerror="window.injectionRan=true">');
  assert.equal(await page.evaluate(()=>window.injectionRan),undefined);
  await send('chart revenue');
  await page.locator('.js-plotly-plot .main-svg').first().waitFor();
  await page.waitForFunction(()=>document.querySelector('.js-plotly-plot')?._fullLayout?.width > 0);
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download CSV'}).last().click();
  const download = await downloadEvent;
  assert(download.suggestedFilename().endsWith('.csv'));
  const pngEvent = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download PNG'}).last().click();
  assert((await pngEvent).suggestedFilename().endsWith('.png'));
  await page.locator('.visualization-container').last().scrollIntoViewIfNeeded();
  await page.screenshot({path:'/private/tmp/smartlook-review-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>{ const e=document.querySelector('.js-plotly-plot'); return e && Math.abs(e._fullLayout.width-e.clientWidth)<3; });
  await page.locator('.visualization-header').last().scrollIntoViewIfNeeded();
  console.log('Chart layout:',await page.locator('.chart-wrapper').evaluate(e=>({width:e.clientWidth,plotWidth:e._fullLayout.width,left:e.getBoundingClientRect().left})));
  await page.screenshot({path:'/private/tmp/smartlook-review-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth),false);
  page.on('dialog',d=>d.accept());
  await page.evaluate(()=>clearConversationHistory());
  assert.equal(await page.locator('.history-item').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS: login, chat, follow-up, reload, separate conversations, resume, HTML escaping, chart rendering, CSV download, mobile overflow, clear history; no browser errors.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
